resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: vinay_github               # Change to your integration
      path: vinayagg/jfrogPipelinesSteps      # Change to your repo
pipelines:
  - name: run_gcloud_cli_docker_image
    configuration:
      environmentVariables:
        readOnly:
          SERVICE_ACCOUNT_JSON: ''
#          GKE_ZONE: ''
#          GKE_PROJECT: ''
#          GKE_CLUSTER: ''
    steps:
      - name: gcloud_login
        type: Bash
        execution:
          onStart:
            - echo "Authorizing access to GKE by service account json file..."
          onExecute:
            - gcloud version
            - echo $SERVICE_ACCOUNT_JSON
            - echo $SERVICE_ACCOUNT_JSON > ./gcloud.serviceaccount.json
            - ls -la
            - cat ./gcloud.serviceaccount.json
            - gcloud auth activate-service-account --key-file=gcloud.serviceaccount.json
            #- gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
          onComplete:
            - echo "gcloud login end"
      # - name: check_gcloud_cli_docker_image_tag
      #   type: Bash
      #   configuration:
      #     inputSteps:
      #       - name: gcloud_login
      #   execution:
      #     onStart:
      #       - echo "Printing gcloud version ..."
      #     onExecute:
      #       - gcloud version
      #     onComplete:
      #       - echo "Checking gcloud version complete."
