resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: vinay_github               # Change to your integration
      path: vinayagg/jfrogPipelinesSteps      # Change to your repo
pipelines:
  - name: run_gcloud_cli_docker_image
    steps:
      - name: check_gcloud_cli_docker_image_tag
        type: Bash
        execution:
          onStart:
            - echo "Printing gcloud version ..."
          onExecute:
            - gcloud version
          onComplete:
            - echo "Checking gcloud version complete."
      - name: gcloud_login
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: google/cloud-sdk
                tag: $gcloud_cli_docker_image_tag
                options: "-e HOME=/root"
          inputSteps:
            - name: jq
        execution:
          onStart:
            - echo "Authorizing access to GKE by service account json file..."
          onExecute:
            - OUT=$(gcloud auth activate-service-account --key-file=$SERVICE_ACCOUNT_JSON 2>&1)
              echo "$OUT"
              if [[ "$OUT" =~ (ERROR) ]]
              then
                failure_response
                exit 1
              fi
              OUT=$(gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT 2>&1)
              echo "$OUT"
          onComplete:
            - echo "gcloud login end"
