resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: vinay_github               # Change to your integration
      path: vinayagg/jfrogPipelinesSteps      # Change to your repo
pipelines:
  - name: pull gcloud docker image
    steps:
      - name: step1
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: cloud-sdk
                tag: latest
                options: "-e HOME=/root"
        execution:
          onStart:
            - echo "Installing missing utils needed by JFrog pipelines"
          onExecute:
            - sudo apt-get install jq gettext -y
          onComplete:
            - echo "Installation complete."
      - name: step2
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: cloud-sdk
                tag: latest
                options: "-e HOME=/root"
          inputSteps:
            - name: step1
        execution:
          onStart:
            - echo "Printing gcloud version ..."
          onExecute:
            - gcloud version
          onComplete:
            - echo "Checking gcloud version complete."
