resources:
  - name: myAppRepo
    type: GitRepo
    configuration:
      gitProvider: vinay_github               # Change to your integration
      path: vinayagg/jfrogPipelinesSteps      # Change to your repo
pipelines:
  - name: run_gcloud_cli_docker_image
    configuration:
      environmentVariables:
        readOnly:
          gcloud_version: 'latest'
    steps:
      - name: download_gcloud_docker_image
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: google/cloud-sdk
                tag: $gcloud_version
                options: "-e HOME=/root"
        execution:
          onStart:
            - echo "Installing missing utils needed by JFrog pipelines"
          onExecute:
            - apt-get install jq gettext -y
          onComplete:
            - echo "Installation complete."
      - name: check_gcloud_cli_version
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: google/cloud-sdk
                tag: $gcloud_version
                options: "-e HOME=/root"
          inputSteps:
            - name: download_gcloud_docker_image
        execution:
          onStart:
            - echo "Printing gcloud version ..."
          onExecute:
            - gcloud version
          onComplete:
            - echo "Checking gcloud version complete."
      - name: gettext
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: google/cloud-sdk
                tag: $gcloud_version
                options: "-e HOME=/root"
          inputSteps:
            - name: check_gcloud_cli_version
        execution:
          onStart:
            - echo "gettext start ..."
          onExecute:
            - gettext
          onComplete:
            - echo "gettext start ..."
      - name: jq
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: google/cloud-sdk
                tag: $gcloud_version
                options: "-e HOME=/root"
          inputSteps:
            - name: download_gcloud_docker_image
        execution:
          onStart:
            - echo "jq start ..."
          onExecute:
            - jq
          onComplete:
            - echo "jq start ..."
      - name: gcloud_login
        type: Bash
        configuration:
          runtime:      
            type: image
            image:
              custom:
                name: google/cloud-sdk
                tag: $gcloud_version
                options: "-e HOME=/root"
          inputSteps:
            - name: gettext
        execution:
          onStart:
            - echo "jq start ..."
          onExecute:
            - jq
          onComplete:
            - echo "jq start ..."
